remote_theme: "mmistakes/minimal-mistakes@4.23.0"
minimal_mistakes_skin: "contrast" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
title: "Far Beyond the Stars Chatlogs"
search: true
search_full_content: true
plugins:
  - jekyll-include-cache
defaults:
  # _docs
  - values:
      show_date: true
      layout: single
      classes: wide
      sidebar:
        nav: "docs"
        - title: "Far Beyond the Stars"
          image: images/cover-350w.png
          image_alt: "cover"
          text: "A Modiphius 2d20 Star Trek misadventure.\nEnabled by Fantasy Grounds Unity.\nPlayed by crazies."